### ISSUE TITLE
Tracking Compliance: Salesforce integration?

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#14]
### Context

ALSF Grants team to be able get stats on resources associated with ASLF Grant IDs to track compliance with resource sharing plans. 

### Problem or idea

ALSF Grants team uses salesforce to manage their grants information. It would be great to add these stats to their database so it fits well into their workflow. 

### Solution or next step
Explore how we can potentially push out stats tracked in the resources portal to the Grants team salesforce database.

**Comment by cgreene** [comment]
Also to add a link to the resource on our portal.

**Comment by davidsmejia** [comment]
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest_resources.htm

Looks like we can push and pull data from salesforce.

Their API requires an auth token that comes with API limits. Though its unlikely we will hit that early on or ever... and looks like you can upgrade should that occur.

I think we can create custom fields in salesforce to store the relevant stats or we can create a custom object type and create new objects that we want to track. 

[Fields](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/custom_fields.htm) and [Objects](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_custom_objects_list.htm#sforce_api_custom_objecst_list) docs

It might be easier to just create a couple custom fields and post them when we create local records on the portal.. Then push the link to that page and it looks like salesforce already has a pattern of refreshing reports data. I'm going to see if there would be a way to tap into that event life cycle.

**Comment by davidsmejia** [comment]
A field would be a key value on a specific grant recipient and an object as far as I can tell would behave as a to-many relationship (like shared resource or referenced resource)

**Comment by kurtwheeler** [comment]
Continued by https://github.com/AlexsLemonade/resources-portal/issues/8
