### ISSUE TITLE
Change "List Resource" to "Add Resources" in Nav Bar + other places

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#162]
### Context
We refer to `List Resource` for both importing or listing resource and only listing resource. It is confusing.

### Problem or idea

Use `Add Resources` when referring to either importing/listing resource. Use `List Resource` when referring to listing a resource with resources portal

### Solution or next step

- Change `List Resource` -> `Add Resources` on the NavBar

- On the following pages
   -  https://invis.io/NAVYSEBXJCF#/414927119_list-Resources-Not-Logged-In  (all versions) 

   - `Resource Listed` -> `Resource Added` https://invis.io/NAVYSEBXJCF#/404889122_resource-Listed

**Comment by kurtwheeler** [comment]
Should be a bug to look out for, but has changed everywhere we've seen so far.
