### ISSUE TITLE
Discuss data model for resources portal

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#18]
We don't have to nail everything down right now, but it'd be good to get a preliminary data model hashed out.

This will be accomplished by a meeting between @kurtwheeler @arielsvn @dvenprasad @davidsmejia

**Comment by arielsvn** [comment]
We created an initial diagram from our discussion https://dbdiagram.io/d/5e14e255edf08a25543fb468

Also, some notes:

- When a new material request is created, it's assigned to the associated contact user in the material.

- The status of a material request will be calculated based on other fields

**Comment by arielsvn** [comment]
We created an initial diagram from our discussion https://dbdiagram.io/d/5e14e255edf08a25543fb468

Also, some notes:

- When a new material request is created, it's assigned to the associated contact user in the material.

- The status of a material request will be calculated based on other fields

**Comment by arielsvn** [comment]
For grants with more than one PI, we'll need a way to give credit to all of them.

A possible solution could use the many-to-many relationship between grants and users. Or we could also have a 'Share Credit' permission where owners of organizations select which people they share the credit with.

**Comment by kurtwheeler** [comment]
We did the thing this issue was for so I'm going to close it.
