### ISSUE TITLE
What's our tech stack?

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#20]
Ticket to track discussion about what we want to use

**Comment by kurtwheeler** [comment]
We met a couple times this week and had a number of discussions about it. We've decided that moving off of Django might be appropriate for this project, but that committing to an unfamiliar stack for such a long project could be risky. Therefore we've decided to implement a portion of the Resources Portal's model and get an API up in both a python flask backend and a javascript express backend.

Other than that we have decided on with:
  - Postgres
  - Terraform
  - AWS
  - ExpressJS on Lambda@Edge (for serving the frontend's SPA)

Frontend:
  - React (FF)
  - Eslint + Airbnb linting rules

I will link to an issue shortly that tracks the test dual implementations.
