### ISSUE TITLE
Set up S3 for attachments

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#217]
### Context

#211 adds a route for attachments.

### Problem or idea

However it doesn't actually put them into S3 because I need to configure that.

### Solution or next step

Hook the attachments route up to S3 and test that files can be uploaded with it.

**Comment by davidsmejia** [comment]
For local envs could we have the endpoints instead of sending to s3, save the file locally. Would probably make sense to add a folder to the repo and git ignore it.
