### ISSUE TITLE
Check models against designs to see if there's anything missing

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#236]
### Context

At this point the backend is nearing completion. Time to check for what's missing.

### Problem or idea

We might need an address model for requests? Is there anything else missing?

### Solution or next step

Check the designs against the model to see if anything else needs to be added to the backend.

**Comment by kurtwheeler** [comment]
I looked at the designs made the following issues:
* https://github.com/AlexsLemonade/resources-portal/issues/244
* https://github.com/AlexsLemonade/resources-portal/issues/245
* https://github.com/AlexsLemonade/resources-portal/issues/246

@davidsmejia can you think of any other things? If so can you create issues for them?

**Comment by cgreene** [comment]
assigning @davidsmejia based on sprint meeting discussion

**Comment by davidsmejia** [comment]
#282 
#283 
#284 
#285 
#286 
#287 
#288
