### ISSUE TITLE
Create initial infrastructure configuration for backend project

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#24]
### Context

I will provide more detail later, but right now I just need an issue to move around.

### Problem or idea

_The context should lead to something, an idea or a problem that you’re facing. Put that here._

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by arielsvn** [comment]
Can we deploy automatically when new commits are pushed to either `master` or `dev`?

**Comment by kurtwheeler** [comment]
For you? Anything!

No but really that seems reasonable.
