### ISSUE TITLE
SRA Importer

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#241]
### Context

Some resources can be imported. SRA datasets is one of these.

### Problem or idea

I imagine the way this will work is that the user will provide a URL/accession (they're kinda interchangable, @dvenprasad which do you prefer we ask for?). This URL/accession will be sent to the backend at a route like `v1/materials/import`. The backend will then use that URL/accession to hit an API and import a material from it.

### Solution or next step

Look at the material model and populate any fields in it that can be populated using the SRA API. See https://github.com/AlexsLemonade/refinebio/blob/dev/foreman/data_refinery_foreman/surveyor/sra.py for code that extracts a lot of fields from their XML. There may be an easier API to use to get the more limited set of fields needed for this project.

**Comment by dvenprasad** [comment]
The form leaves it up to the user which one they want to input. Is that okay or do we need to restrict them to either URL or Accession?

**Comment by kurtwheeler** [comment]
Nope, we can accept either! It should be easy to pull the accession out of the URL.
