### ISSUE TITLE
Material Request Additional Documents

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/resources-portal#298]
We need to prevent the requester from uploading the documents piece meal after their material_request has been accepted 

It would be great to validate the update on material request when the requester tries to attach their IRB, partially executed MTA, and shipping codes - we ensure that they are all sent in the same request.

**Comment by kurtwheeler** [comment]
@davidsmejia is this still relevant or did we end up addressing this in some manner?

**Comment by davidsmejia** [comment]
> @davidsmejia is this still relevant or did we end up addressing this in some manner?

Looks like this was taken care of! https://github.com/AlexsLemonade/resources-portal/blob/dev/api/resources_portal/views/material_request.py#L104

Cant find the PR but here is the commit
https://github.com/AlexsLemonade/resources-portal/commit/46d6604cd84cab2289a3a84d10f3fc784ae2cfea

Closing since this was addressed.

**Comment by davidsmejia** [comment]
Actually this is still relevant since we do not check that any of the updates are completely updated.
For example if you need the IRB and the partially executed MTA this issue is saying we should force the user to post them at the same time instead of allowing one then the other. This helps simplify a lot of the logic for determining the current state of the request.

I'm not 100% sure at the moment if doing that would break the client - seems possible. But I do know the client does not allow the user to do that. So this is mainly a nice to have for overall system integrity. Meaning the API backs up what the client is coercing the user to do.
