### ISSUE TITLE
Notifications Endpoint and Attributes

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/resources-portal#299]
Notifications need to be able to be listed in the users Account section of the site.

Also we will need to be able to link to the request when the notification is tied to a request so the ID would be required to generate that link.

![Screen Shot 2020-08-06 at 4 28 16 PM](https://user-images.githubusercontent.com/1075609/89579475-d64a9380-d801-11ea-85cd-fa4941362c1a.png)

**Comment by davidsmejia** [comment]
I believe we have everything needed outside of the link to a request so request_id should be added, also would be nice to have user/id/notification to show everything that user should be able to see via permissions

**Comment by davidsmejia** [comment]
Also, small critique these names are a little verbose no?

`associated_material_id`
`associated_organization_id`
`associated_user_id`

**Comment by kurtwheeler** [comment]
Closed by #390
