### ISSUE TITLE
Listing Resources: Scope, Requirements, Design Decisions

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#3]
### Relevant use cases:

**One**

Applicable to: Sharers

I’m a PI studying effects of a drug in medulloblastoma tumors. I’ve generated a PDX mouse model which I have demonstrated to be more effective than current models. I have not found an appropriate repository for my model, but I would like to make it more visible to the broader community. I currently have it in my lab and have the resources to create and send the models to researchers on request.

**System Actions**:

1. Sharers must be able to sign up or sign in with their ORCID
2. Sharers must be able to list PDX mouse models
3. Sharers should be able to give restricted access to members of their lab who are fulfilling the request.

**Two**

Applicable to: Sharers

**Addresses: HMW Ease the burden of listing resources**

I have a plasmid which I have already listed on AddGene. I have been mandated to list all my resources in a different portal as part of a grant. I don’t want to go through the trouble of re-listing the same information again.

**System Actions:**

1. Sharers must be able to “import” information from AddGene or other repositories into the portal
2. Requesters will be redirected to AddGene to make the requests.

**Ten**

Applicable to: Sharers

I have recently received a grant and I am expected to list all the data I generate with the grant on a portal. I expect to generate different data at various intervals. I would rather list them as I generate rather than wait till the end of the grant period. I don’t want the data to be public until I publish though. When I do publish, I will need to list them on GEO or SRA.

**System Actions:**

1. Sharers must be able to add resources privately or save them as drafts until they are ready to publish it.
2. Sharers must be able to associate different resources to the same study.
3. ~Sharers must be able to export their listing to GEO or SRA.~ (not in scope)

**Thirteen**

Applicable to: Sharers, Requesters

**Addresses: HMW ease the burden of legal paperwork**

I have approved a request for mouse model. I need to get an MTA in place before I can go about fulfilling the request.

**System Actions:**

1. Sharers will be prompted to upload an MTA when listing their resources, if applicable.
2. Requesters will receive the MTA when their request is approved and they will need to sign it and upload it before Sharers can begin fulfilling their request.

**Fourteen**

Applicable to: Sharers

I’ve listed some scRNA-seq data on GEO when I published as mandated by the journal. Now my grant period is coming to a close and I am required to add scRNA-seq data to this portal as well.

**System Actions:**

1. Sharers must be able to add a resource with a GEO accession code
2. Requesters will be redirected to GEO to download the data.

### Problem or idea

**Workflow:**
![Resources Portal Workflow - List Resources](https://user-images.githubusercontent.com/15315514/68872281-c6b37980-06cb-11ea-84b8-f63904967019.jpg)

Features/ideas not in diagram:
- Allow corrections on scraped fields

### Solution or next step
Whiteboarding session to dig deeper into the details of the workflow and work on layouts for low-fi.

**Comment by arielsvn** [comment]
We created an initial diagram from our discussion https://dbdiagram.io/d/5e14e255edf08a25543fb468

Also, some notes:

- When a new material request is created, it's assigned to the associated contact user in the material.

- The status of a material request will be calculated based on other fields

**Comment by dvenprasad** [comment]
Notes from the white boarding session:
![IMG_20200109_130657_1](https://user-images.githubusercontent.com/15315514/72098060-c14d6680-32eb-11ea-98f4-2aa7170d926e.jpg)


- Scrape experiment level data for GEO/SRA
- dbGaP is not scrap-able, protocols.io may be. 
- If data in GEO/SRA are in embargo, default to template and prompt for embargo date so we can scrape the info then. 
- For resources we aren't currently supporting(don't have templates for) ask users for title and description( for now) . Handle adding custom fields later
- Fields for the template are update here:
  - [Plasmid](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346997702393)
  - [Datasets](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998016982)
  - [Scientific Source Code](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998104708)
  - [Cell Lines](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998017229)
  - [Protocols](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998227589)
  - [Bio Samples](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998247828)
  - [Model Organisms](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346997727657)

@arielsvn @cgreene @annagreene let me know if I've missed anything related to this workflow.

Next steps: I will create low-fi screens for this flow

**Comment by dvenprasad** [comment]
**Summary of major changes from the Low-fi review:**
- Ensure that people can re-use request requirements from other resources. @kurtwheeler suggested we store different combinations of request requirements users have used in the past like websites store credit card info. 

- Revamp the fields for listing biosamples using NCBI's biosamples as reference

- Modify and add fields for Plamids based on AddGene's deposit a plasmid xls sheet

- Editing fields in review: Add an edit button per section and they take users back to that section to edit the fields 

**A few things we need to look into:**
- biosafety levels and associate them with biosamples and model organisms
- IACUC certification(?) for model organism handling. 

There were a few other minor changes which I have noted on Invision


**Next steps:**
I would like do another round of low-fi only for re-using request requirements before moving to the high-fi iteration
The rest of the changes can be addressed in high-fi mockups. 


**Low-fi Screens (for record)** 
![list-getting-started](https://user-images.githubusercontent.com/15315514/72643725-5e884a80-393d-11ea-92bd-94063342a3cc.png)
![list-resources-start-here](https://user-images.githubusercontent.com/15315514/72643726-5e884a80-393d-11ea-8120-e1c46611e3e1.png)
![list-review-dataset](https://user-images.githubusercontent.com/15315514/72643727-5e884a80-393d-11ea-80d3-b42ea55d1921.png)
![list-review-plasmid](https://user-images.githubusercontent.com/15315514/72643728-5e884a80-393d-11ea-8da8-e8225d341f79.png)
![list-request-requirements](https://user-images.githubusercontent.com/15315514/72643730-5e884a80-393d-11ea-8191-0f5c32d2cb4b.png)
![list-other](https://user-images.githubusercontent.com/15315514/72643731-5e884a80-393d-11ea-9ce2-6e65800daec5.png)
![list-protocol](https://user-images.githubusercontent.com/15315514/72643732-5e884a80-393d-11ea-96fa-b2f1d6e26076.png)
![list-model-org](https://user-images.githubusercontent.com/15315514/72643733-5e884a80-393d-11ea-969b-c7603bad12e2.png)
![list-plasmid](https://user-images.githubusercontent.com/15315514/72643735-5f20e100-393d-11ea-913c-b606a515cfb3.png)
![list-cell-line](https://user-images.githubusercontent.com/15315514/72643736-5f20e100-393d-11ea-9e92-d0ff920dda38.png)
![list-dataset](https://user-images.githubusercontent.com/15315514/72643738-5f20e100-393d-11ea-9502-6210e69cc1a2.png)
![list-biosample](https://user-images.githubusercontent.com/15315514/72643740-5f20e100-393d-11ea-8f3e-cf9f5c42e619.png)
![import-resources-alt-dbgap](https://user-images.githubusercontent.com/15315514/72643741-5f20e100-393d-11ea-8f02-79a407c7b7a1.png)
![import-resources-alt-jax](https://user-images.githubusercontent.com/15315514/72643742-5f20e100-393d-11ea-953e-78e3a759d5a8.png)
![import-resources-alt-protocolsio](https://user-images.githubusercontent.com/15315514/72643743-5f20e100-393d-11ea-9e07-2c619e2fecb3.png)
![import-resources-alt-not-reco](https://user-images.githubusercontent.com/15315514/72643744-5f20e100-393d-11ea-8b2a-b531c780850f.png)
![import-resources-not-recognized](https://user-images.githubusercontent.com/15315514/72643745-5fb97780-393d-11ea-92f5-368a0890a602.png)
![import-resources-addgene](https://user-images.githubusercontent.com/15315514/72643746-5fb97780-393d-11ea-87a0-95ceb52a69fe.png)
![import-resources-atcc](https://user-images.githubusercontent.com/15315514/72643748-5fb97780-393d-11ea-8404-5cac06449499.png)
![import-resources-GEO-SRA-embargo](https://user-images.githubusercontent.com/15315514/72643749-5fb97780-393d-11ea-94e3-19df1aa71822.png)
![import-resources-GEO-SRA](https://user-images.githubusercontent.com/15315514/72643750-5fb97780-393d-11ea-8051-eb0cbfe39e9a.png)
![import-resources-enter-URL](https://user-images.githubusercontent.com/15315514/72643751-5fb97780-393d-11ea-8ba5-7c01b01be9d3.jpg)

**Comment by dvenprasad** [comment]
For more accessible documentation: (this info is on invision)

These are the resources which can be imported/listed

Import from:
GEO/SRA (dataset)
dbGaP (dataset)
ATCC (cell line)
Add Gene (plasmid)
protocols.io (protocols)
Jackson Lab (Model organisms - mouse specific repo)
ZIRC/ZFIN (Model organisms - zebrafish specific repo)
Other

List: 
- Cell Line
- Dataset
- Model Organism
- Plasmid
- Protocol
- PDX
- Other

PDXs can be listed, but not imported.

**Comment by dvenprasad** [comment]
**Summary of Changes:**
- Added non-editable view of imported resources (GEO/SRA and protocols.io)

- Added a set of `Additional Details` fields for every resource.
  - For listed resources and import from Jackson Lab, Other, and ZIRC. Citation is included for Jackson lab and ZIRC since there isn't clear information about citation on their websites. 
    <img width="477" alt="Screen Shot 2020-03-31 at 10 05 28 PM" src="https://user-images.githubusercontent.com/15315514/78091722-c0344e80-739b-11ea-92dc-8c75ced23f4e.png">

  - For Imported resources
     <img width="350" alt="Screen Shot 2020-03-31 at 10 07 40 PM" src="https://user-images.githubusercontent.com/15315514/78091844-0ee1e880-739c-11ea-8204-949dc17dd2fc.png">

- For Publication Title and Pre-print Title, we will try to retrieve them real time, based on PubMed ID and Pre-print DOI fields respectively. If we fail, we should prompt them to fill it out.

- Added Patient Derived Xenograft (PDX) Models as a resource. 

- Dropped Bio Samples for MVP.


There are way too many screens, it doesn't make sense to add it here. I'm going to only link to Invision instead. All of the relevant screens are under `List Resources` section.
 
**Invision Link**
https://invis.io/NAVYSEBXJCF

@arielsvn @davidsmejia let me know if you need more things from me.
