### ISSUE TITLE
Change relationship endpoints to accept the two objects being related

### ISSUE THREAD

**Issue by Philinphiladelphia** [AlexsLemonade/resources-portal#316]
### Context

For endpoints which govern the relationships between two objects (like organization_user_setting), it would be nice if the URL accepted two IDs instead of an ID for the relationship object.

### Problem or idea

Check through all the endpoints and find if relationships need to be changed.

### Solution or next step

Change them.

**Comment by kurtwheeler** [comment]
I think it's too late to make a change like this.
