### ISSUE TITLE
Exception when PATCH sent to /attachments/[id]

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/resources-portal#325]
### Context

Was having an issue updating an attachment looks like in the permissions check.

I think this should be something like `obj.owned_by_org in request.user.organizations.all()`
Which would mean it would pass if the user is in an organization that the attachment belongs to.

```AttributeError: 'NoneType' object has no attribute 'members'```

https://github.com/AlexsLemonade/resources-portal/blob/dev/api/resources_portal/views/attachment.py#L58

If this tracks @kurtwheeler could you take a look into this as well:

I think this also exposes a need to pass an organization id when creating an attachment. Since this is my Personal org which I am owner but not a member of.

If I wanted to update this as a member of an org I don't see how the attachment would know it is kosher unless that org_id was set so we should probably require it (or check every relationship ie attachment->[sequence_map_for]->organization->members + owner.

**Comment by kurtwheeler** [comment]
> attachment->[sequence_map_for]->organization->members + owner

I think is maybe the right thing to do. I wonder if we should just insist that owners are always members of the org. I think that might be simpler in a lot of ways and it makes more sense to me semantically.
