### ISSUE TITLE
Create /report-issue endpoint

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/resources-portal#345]
### Context

The client has a few buttons that allow the user to report issues with their grants.

### Solution or next step
Add a `/report-issue` [POST] endpoint that takes one key in the body of the request: `message`.
The endpoint should be authenticated, and pull the users name, email, existing grants, existing orgs, and their message.

We should send it to the grants team and return 201 created, 401 if not authorized.

The grants team email should also be an env var

**Comment by davidsmejia** [comment]
Also should create a notification for the user that sent it

**Comment by dvenprasad** [comment]
Copy
```
Subject: Request for <resource type> escalated 
Body: Request for <resource type>, <resource name> has been escalated to the grants team. 
ALSF Grants team is looking into this and will be in touch with you soon. 
Below is the message they received from you for your records.

"<message> "

Plain Text
<Full Name>,
Request for <resource type>, <resource name> has been escalated to the grants team. 
ALSF Grants team is looking into this and will be in touch with you soon. 
Below is the message they received from you for your records.

"<message>" 

The CCRR Team
-----
You are receiving this email because you subscribed to receive notifications from CCRR portal. Manage Notifications
Alex's Lemonade Stand Foundation
111 Presidential Blvd, Suite 203, Bala Cynwyd,  PA 19004
```

@kurtwheeler

**Comment by kurtwheeler** [comment]
The route exists, remaining work being tracked in https://github.com/AlexsLemonade/resources-portal/issues/374
