### ISSUE TITLE
Component Library Showcase

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/resources-portal#36]
### Context

We want to see how he components behave and are implemented.

### Problem or idea

Add a page to the frontend client that lays out (single file) how the components look

### Solution or next step

after #35 
- [ ]  add [evergreen](https://evergreen.segment.com/components) 
- [ ]  add `/forms-demo`

**Comment by arielsvn** [comment]
Looks like evergreen supports tree-shaking https://github.com/segmentio/evergreen/issues/458#issuecomment-442231720, although it might need a bit more configuration for the icons package.

**Comment by davidsmejia** [comment]
Moved to Grommet as it comes with more components that we would need, though I am thinking it might make sense to use this just as an abstraction for forms.

**Comment by davidsmejia** [comment]
closing with #72
