### ISSUE TITLE
Trouble Paginating /materials endpoint

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/resources-portal#368]
I seem to be unable to set a limit or filter the materials endpoint

I have tried filtering `organization` and `organiation_id`
Also `limit` doesn't seem to be respected.

It does return a "paginated" response in that it contains results, count, next and prev but no indication that it applied any of the params

**Comment by kurtwheeler** [comment]
Closed by https://github.com/AlexsLemonade/resources-portal/pull/376
