### ISSUE TITLE
Weekly notification digest

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#372]
### Context

#346 does not send the weekly digest of notifications

### Problem or idea

Create a cron job to send the digest email every week. Probably using a management command.

### Solution or next step

See the attached zip file from @dvenprasad for what the emails should include: [weekly_digest.zip](https://github.com/AlexsLemonade/resources-portal/files/5163072/weekly_digest.zip)

**Comment by kurtwheeler** [comment]
@dvenprasad is there a plain text version of this?

**Comment by dvenprasad** [comment]
``` 
<Full Name>,
You received <X> notifications for the week of <date>.
--

<notification date>
<notification email copy>
<cta>


<notification date>
<notification email copy>
<cta>


<notification date>
<notification email copy>
<cta>


<notification date>
<notification email copy>
<cta>


The CCRR Team
-----
You are receiving this email because you subscribed to receive notifications from CCRR portal. Manage Notifications
Alex's Lemonade Stand Foundation
111 Presidential Blvd, Suite 203, Bala Cynwyd,  PA 19004
```

<notification email copy> -> this is the body of the corresponding notification. 
I would add 2 line breaks between each notification to create visual break (alternate would be to use `----` but that becomes visually noisy fast.)
