### ISSUE TITLE
View Resources: Scope, Requirements, Design Decisions

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#4]
### Relevant Use Cases

**Three**

Applicable to: Sharers, Requesters

**Addresses: HMW Help researchers handle post-sharing communications about the resources**

I have listed a cell line on the portal. I receive a lot of emails asking very similar questions about the cell line from different researchers and takes up a good chunk of my week responding to these emails. I wish there was a less burdensome way to do this.

**System Actions:**

1. Requesters can ask questions about the resource publicly.
2. Sharers should be able to respond publicly to questions and clarifications about a resource.

**Eleven**

Applicable to: Requesters

I am looking for cell lines with knock in with my gene of interest. I want some way to get an idea of the “quality” of the cell line.

**System Actions:**

1. Requesters should be able to search by genes, filter by technique.
2. Requesters should be able to get passage information for cell lines
3. Requesters should be able to view STR profile or sequencing information

**Twenty-two**

Applicable to: Requesters

I found a study with two resources, tumor cell lines and their whole exome-sequencing data which I am interested in. The study also have some other related resources. I would like to get all the resources from the study.

**System Actions:**

1. Allow Requesters to make requests on a ~study level~ Grant ID basis.

### Problem or idea

![Resources Portal Workflow - View Resource](https://user-images.githubusercontent.com/15315514/68879014-afc65480-06d6-11ea-8e9f-ddd87f9f6924.jpg)

Resource Details:
- [Plasmid](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346997702393)
- [Datasets](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998016982)
- [Scientific Source Code](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998104708)
- [Cell Lines](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998017229)
- [Protocols](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998227589)
- [Bio Samples](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346998247828)
- [Model Organisms](https://miro.com/app/board/o9J_kwI2PHs=/?moveToWidget=3074457346997727657)

### Solution or next step
Whiteboarding session to dig deeper into the details of the workflow and work on layouts for low-fi.

**Comment by dvenprasad** [comment]
**Low-fis**

### PDX
![view-pdx-details](https://user-images.githubusercontent.com/15315514/78253749-d7ba2700-74c2-11ea-996f-a6249bc7c20d.png)

![view-pdx-contact](https://user-images.githubusercontent.com/15315514/78253728-d12baf80-74c2-11ea-8bcf-0771d807dc38.png)

![view-pdx-publication](https://user-images.githubusercontent.com/15315514/78253740-d4bf3680-74c2-11ea-90df-765b4692f03a.png)

![view-pdx-request-requirements](https://user-images.githubusercontent.com/15315514/78253707-cc66fb80-74c2-11ea-932c-802427f3eab9.png):

### ATCC

![view-atcc](https://user-images.githubusercontent.com/15315514/78253694-c6711a80-74c2-11ea-8c54-01ecc5826e83.png)

**Comment by dvenprasad** [comment]
**Summary of Changes**

- Removed request stats

- Reorganized `Request requirements` tab to present information more clearly. 

- Added `Publication Information` tab to imported resources view.

There are too many screens to post there. Going to post an example of Listed Cell Line and a cell line imported from ATCC and **the rest can be found on Invision.**

![view-cell-line](https://user-images.githubusercontent.com/15315514/78254928-9cb8f300-74c4-11ea-85a4-2f2c57552753.png)

![view-atcc](https://user-images.githubusercontent.com/15315514/78254929-9dea2000-74c4-11ea-800f-8dce05e6c342.png)

**Invision Link**
https://invis.io/NAVYSEBXJCF#/408945792_view-Cell-Line

@arielsvn @davidsmejia let me know if you anything else from me.

**Comment by arielsvn** [comment]
Created #92  to start implementing this page @dvenprasad, can we close this one?
