### ISSUE TITLE
Additional detail fields on imported protocol/GEO pages

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#473]
### Context

When users import protocols/dataset, the`Additonal Details` fields like pubmed ID, publication title, contact authors doesn't show up but when you edit it, those fields are pre-filled and present. 
![Screen Shot 2020-10-02 at 2 37 07 PM](https://user-images.githubusercontent.com/15315514/94958227-2b7eea80-04bd-11eb-9382-afc6b953289e.png)

### Problem or idea

Show `Additional Details` fields on Review page. 

![Screen Shot 2020-10-02 at 2 40 25 PM](https://user-images.githubusercontent.com/15315514/94958256-3a659d00-04bd-11eb-9590-c7b9b92080b7.png)

**Comment by davidsmejia** [comment]
I dont think we need contact info for imported resources? But also we can add the edit publication edit fields to this form
