### ISSUE TITLE
Back button when listing 

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#478]
### Context

![Screen Shot 2020-10-02 at 3 19 25 PM](https://user-images.githubusercontent.com/15315514/94961463-b1e9fb00-04c2-11eb-80c4-f4d62fb1ad93.png)

### Problem or idea

We need to add a back button here to take them to the previous page i.e the resource form.
Also the back button on the browser needs to taken users back to the form. Currently it takes them the `Add Resources` page.

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by kurtwheeler** [comment]
Changing the behavior of the browser's back button is more involved and should be a separate feature request.

I think this issue's scope can just be for the back button on the page.
