### ISSUE TITLE
Handle Draft Saves

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/resources-portal#48]
### Context

Related to #37 

Some forms will either require functionality to handle autosave or draft saves.
The models for the API should be able to handle model state saves that can be invalid ie. missing required fields.

### Problem or idea

i don't think that the current API models can save missing values if required fields are handled via postgres.

### Solution or next step

We could create an arbitrary data store for the frontend forms with a model called `UserData` which has the following fields: 
`id`, `user_id`, `key`, `created_at`, `updated_at`

The front end should be able to list out these drafts and provide a mechanism to delete old ones if the user wants to. 

Something with this flow

`POST:`
`  url: /user_data/{key}`
`  body: {data: {'valid': 'json'}"`
`  header: token=XXXX`

`GET:`
` url: /user_data/{key}`
` header: token=XXXX`
` response: {results: [{id: 'xx-xxx-xx', data:{'valid': 'json'}, updated_at: 'XXX'}]}`

`PUT:`
` url: /user_data/{key}/xx-xxx-xx`
` header: token=XXXX`
` body: {data:{'valid': 'json2'}}`

`DELETE:`
` url: /user_data/{key}/xx-xxx-xx`
` header: token=XXXX`
` response: {status: 410}`

**Comment by cgreene** [comment]
Goal for this sprint: decide on a solution to handle this.

**Comment by davidsmejia** [comment]
We are going to go ahead and handle this on the front end for MVP but keeping in mind that we will want to be able to send this to the API in the future.
