### ISSUE TITLE
Cell Line search card missing fields

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#481]
### Context
the cell line search card has missing fields
![Screen Shot 2020-10-02 at 3 42 04 PM](https://user-images.githubusercontent.com/15315514/94963255-d693a200-04c5-11eb-9fbe-72daf25a0fb9.png)

### Problem or idea

Tissue histology and Quality fields are not populated. 
Field name `Request Requirements` is missing.
Publication/Pre-print field is missing

### Solution or next step
it should look like: 
![Screen Shot 2020-10-02 at 3 42 44 PM](https://user-images.githubusercontent.com/15315514/94963304-ee6b2600-04c5-11eb-84c2-21e541ef46c8.png)

**Comment by kurtwheeler** [comment]
Closed by #481
