### ISSUE TITLE
Create a set of test data 

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#50]
### Context

https://github.com/AlexsLemonade/resources-portal/issues/49

### Problem or idea

We're going to have a number of end to end tests that will all need a set of common data. This data should be easy to create for each of those tests.

### Solution or next step

Create a function that will populate the test database with:
- [x] Contains three users:
  - [ ] PrimaryProf: Has her personal org and a lab organization called PrimaryLab.
    - [ ] Has notifications turned off.
  - [ ] Postdoc: has approval permission for PrimaryLab.
    - [ ] Has notifcations for requests turned on.
  - [ ] SecondaryProf: has a personal org.
    - [ ] Has default notifcations.
- [x] Contains four orgs:
  - [ ] One for the PrimaryProf's personal organization
  - [ ] and one for her lab PrimaryLab
  - [ ] One for the postdoc
  - [ ] One for the SecondayProf
- [x] Contains seven resources listed under PrimaryLab:
  - [ ] Cell line
  - [ ] Plasmid
  - [ ] Protocol
  - [ ] Dataset
  - [ ] Mouse model
  - [ ] Zebrafish Model
  - [ ] PDX
- [x] Contains a two grants:
  - [ ] One for PrimaryProf
  - [ ] One for SecondaryProf

**Comment by dvenprasad** [comment]
- Would it be helpful to have some resources which have been imported? or Were you thinking that some of the resources in the list above would be imported?

- PDX is another resource type which not in that list. We added it in when doing the search/filter/view modules.

**Comment by kurtwheeler** [comment]
Added PDX :+1: 

> Would it be helpful to have some resources which have been imported? or Were you thinking that some of the resources in the list above would be imported?

Mmm good point!!! We're only supporting importing some types of resources right? For the ones that are imported, will we also support listing them? Do you have a breakdown somewhere of which can be imported and which cannot?

I think that we should have both a listed and imported resource of each type that can be imported. Cover all the types of data!!

**Comment by dvenprasad** [comment]
They are written down as comments on import and list screen on Invision.  
Made  https://github.com/AlexsLemonade/resources-portal/issues/3#issuecomment-605287481 now (seemed the most appropriate place to put it.)

**Comment by cgreene** [comment]
Write the test data as JSON files.

**Comment by kurtwheeler** [comment]
"Write the test data as JSON files" was in reference to #46, not this one. These should be created using factories in the `api/resources_portal/test/` directory.
