### ISSUE TITLE
Crash in My Account > Basic Information

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/resources-portal#509]
### Context

I was poking around the "My Account" section to see what was there, and on clicking "Basic Information" I got a crash.

### Problem or idea

Before the Sentry crash report popped up, the screenshot would have looked incredibly similar to what @jashapiro put on #506.

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by kurtwheeler** [comment]
@jaclyn-taroni has this persisted past you actually getting an account?

**Comment by jaclyn-taroni** [comment]
No I think this had been resolved!

**Comment by kurtwheeler** [comment]
Excellent!
