### ISSUE TITLE
Create notification table

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#51]
### Context

I've created a set of end to end tests for us to implement: https://github.com/AlexsLemonade/resources-portal/issues/49

### Problem or idea

We've decided to go with a notification table! I'm leaving the rest of the ticket as it was to show why/what this should be, but now instead of a question ticket it's an implementation ticket!

I would like to be able to test what notifications go to who for each of these tests. I'd like it to be easy, and automatically fail the test if any unexpected notifications happen. This way we won't have to test that notifications don't happen in each test, we can just test what notifications should happen and then we'll be very explicit about them so we'll get good testing around our notification system.

### Solution or next step

So far I've come up with two ideas of how we can do this:
#### We could create a notification table tracking what notifications went to which users.
Pros:
  * This could potentially be useful if we ever wanted to analyze how many notifications we send to gauge how chatty our app is.
  * This could potentially be useful when looking into non-compliant users?

Cons:
  * It's an entire table we might not need
  * If we had 1000 users generate 100 notifications each it'd 100k rows, so we're looking at fairly tiny data, but it's still more data we're paying to have in our database.

#### OR

 We could just have a notify function that we use to trigger notifications and then mock that out in all the tests. Then we just have to compare the calls to that mock function to the expected notifications.

@dvenprasad @cgreene @arielsvn @davidsmejia I'd appreciate any thoughts or opinions on this.

**Comment by cgreene** [comment]
I think I like the notification table. If it ends up being too large/costly, we can always trim it (or rotate it, or similar). 100k rows isn't that much, and that's at a level where we have far more users than we're expecting with the initial rollout. Plus easier debugging is always a win.
