### ISSUE TITLE
Creating team and adding members 

### ISSUE THREAD

**Issue by envest** [AlexsLemonade/resources-portal#511]
### Context

I signed in and my first instruction was to add members to a team. I clicked a link which took me to this page:

<img width="1438" alt="Screen Shot 2020-10-08 at 4 35 20 PM" src="https://user-images.githubusercontent.com/10382980/95513022-a6e20f80-0987-11eb-99c8-dcb76eb16fd9.png">

### Problem or idea

Nothing shows up for me on this page. Just the wobbly lemon (which I love)

### Solution or next step

What I imagine exists here is... a table of existing teams I am part of and my role and a button that says "create team". Each existing team in the table might have a button that says "add members".

**Comment by kurtwheeler** [comment]
I think this may have been an intermittent error (we're working on a good resolution for that).

Can you give this another shot? The page seems to be loading for me.

**Comment by envest** [comment]
Thanks... I got the same non-loading event today multiple times :/

My steps:
1. Navigate to https://staging.resources.alexslemonade.org/create-account?grant_title=Steven%27s%20Grant&grant_funder_id=ALSF&grant_title=Steven%27s%20Other%20Grant&grant_funder_id=ALSF
2. Click "Sign in with ORCID ID"
3. Enter my real email (stevenmasonfoltz@gmail.com)
4. Verify grant information ("This information is correct")
5. On Next Steps, I click "Add members of your lab..."
6. My Account > Team page shows a lemon
7. My Account > Notifications looks like I expect
8. My Account > Manage Resources == has a header and a lemon
9. My Account > Requests == just a lemon
10. My Account > Basic Information == "Uh oh, something happened" + dialog box for reporting an issue

**Comment by envest** [comment]
This is resolved from my perspective

**Comment by kurtwheeler** [comment]
Sweet I think it can be closed then!
