### ISSUE TITLE
New Favicon needed.

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/resources-portal#512]
### Context

I had many tabs open, and was looking for the one with the CCRR...

### Problem or idea

The current favicon at https://github.com/AlexsLemonade/resources-portal/blob/dev/client/public/favicon.ico is a triangle, which is not very distinctive or on brand.

### Solution or next step

Replace the favicon with a fun little lemon (or something else distinctive!)

**Comment by dvenprasad** [comment]
We should use the lemon on alexslemoade.org since this gonna get tucked under alexs domain.

**Comment by davidsmejia** [comment]
need to update this to the new branding
