### ISSUE TITLE
Unable to retreive email address from ORCID shows up everytime I log in

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/resources-portal#514]
### Context

I'm going to preface this with the fact that this may entirely be a function of using ORCID Sandbox with a mailinator email address, but I found this behavior odd.

I had created a sandbox ORCID account using a `mailinator.com` email address. The instructions for internal eval guidelines were to use a _real email address_ for testing notifications, which I did the first time I logged in.

### Problem or idea

Every time I go back to staging, I click on `Sign in with ORCID iD` and then select `Sign in with ORCID iD` in the modal. I log in with the sandbox account and every time I come back to the portal I get the following:

<img width="1421" alt="Screen Shot 2020-10-09 at 9 19 02 AM" src="https://user-images.githubusercontent.com/19534205/95588833-ece3b580-0a11-11eb-8d45-d951653ae4d5.png">

I would expect to only need to associate with my real email address one time.

### Solution or next step

The first step is to evaluate whether this was worth reporting/indicative of something larger or just an artifact of the testing conditions.

**Comment by kurtwheeler** [comment]
This was caused by the same issued as #517.
