### ISSUE TITLE
Sentry dialog box opens once per error instead of once per page

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#515]
### Context

We've got a known issue with notifications

### Problem or idea

When I go to list my notifications I get the error dialog box with a black border. When I click close, it stays, except the border gets less dark each time I click it until it's gone.

### Solution or next step

I think it's because it opens up one dialog box per error, which is probably one per notification. Ideally we'd only open one box per page and/or interaction.

**Comment by kurtwheeler** [comment]
@davidsmejia this is done correct?

**Comment by davidsmejia** [comment]
> @davidsmejia this is done correct?

No this is not done. I think we will want to roll out our own version of the SentryErrorBoundary and handle that. I am not sure at the moment how we would be able to do that and keep the dialogue box though.
