### ISSUE TITLE
Notification expected after listing a resource?

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/resources-portal#516]
### Context

Per my instruction to `List a resource, require Abstract, Shipping, IRB, and MTA as request requirements`, I clicked the `Add a Resource` tab and was led to the following page:

<img width="1142" alt="Screen Shot 2020-10-09 at 9 35 11 AM" src="https://user-images.githubusercontent.com/43576623/95589784-3c76b100-0a13-11eb-999d-542c50c2077a.png">

I then clicked on each of the recommended repos which all led me to the link: https://www.atcc.org/Services/Deposit_Services.aspx (after I created an ATCC profile). Is this the expected behavior?

I was led to a form when attempting to list a resource with ATCC, so I went back to try "list with us" and was able to list the resource per my instructions.

### Problem or idea

However, upon listing the resource, it seems like things crashed briefly but came back and showed me my listed resource. It then showed me that I had 1 Notification waiting, but I each time I hit the Notification tab, I am encountered with: 

<img width="1278" alt="Screen Shot 2020-10-09 at 10 27 12 AM" src="https://user-images.githubusercontent.com/43576623/95595313-05f06480-0a1a-11eb-8ec8-5e2fbef887e6.png">

<img width="1142" alt="Screen Shot 2020-10-09 at 10 17 51 AM" src="https://user-images.githubusercontent.com/43576623/95595161-de999780-0a19-11eb-8037-3fceb5beab15.png">

### Solution or next step

Beyond not receiving a notification in the portal, I also did not receive one via email. Was I suppose to receive one when listing the resource or does is this behavior only expected to occur once a user requests the resource?

**Comment by kurtwheeler** [comment]
I think this is the combination of #664 and #477, so I'm going to close it since it's tracked elsewhere.
