### ISSUE TITLE
Stuck in a Sign in to Request loop

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/resources-portal#517]
### Context

One of my tasks for testing was to request Chante's resource. I am unable to complete a request.

### Problem or idea

After searching for Chante's resource and viewing it, the action button says `Sign in to Request`. 

<img width="1613" alt="Screen Shot 2020-10-09 at 11 31 03 AM" src="https://user-images.githubusercontent.com/19534205/95602439-ee69a980-0a22-11eb-902f-8e81f8ae2490.png">

When I try to sign in to request, I go through the sandbox ORCID steps and I'm brought to my account page where I need to associate with an email address again (#514).

The portal never registers that I'm signed in as far as the page for Chante's resource is concerned and I am unable to complete the request.

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by jaclyn-taroni** [comment]
I added a last name to my sandbox ORCID and then was able to log in.

**Comment by kurtwheeler** [comment]
Missing a last name is no longer an issue.
