### ISSUE TITLE
My request has been accepted, now what do I do?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/resources-portal#522]
### Context

Chante accepted my request. I received an email with the subject line `Action required: Request for DATASET accepted`. The contents of the email are just the ALSF logo. 

### Problem or idea

It's not clear what I'm supposed to do from this email. When I navigate my notifications in the app, it looks like this:

<img width="1294" alt="Screen Shot 2020-10-09 at 12 29 10 PM" src="https://user-images.githubusercontent.com/19534205/95608610-5fad5a80-0a2b-11eb-916d-d3f09419ddf3.png">

Where there are some conditions for acceptance. It's not clear to me what I should do next from this page. If I click on the name of the resource, it takes me to the page for that resource which is not unexpected, it's just not clear to me how to complete the required action from the email or in-app notification.

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by kurtwheeler** [comment]
I think this will be resolved by having one clear CTA per nottification: https://github.com/AlexsLemonade/resources-portal/issues/647
