### ISSUE TITLE
Can not complete awaiting additional documents steps

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/resources-portal#524]
### Context

After #522, I figured out that I needed to navigate to `Requests` > `Sent requests` to complete the additional steps. 

### Problem or idea

I get an error banner (but no Sentry crash report modal) `Unable to update` when I try to hit the `Submit` button.

<img width="1882" alt="Screen Shot 2020-10-09 at 12 36 38 PM" src="https://user-images.githubusercontent.com/19534205/95610285-10b4f480-0a2e-11eb-9cd1-42af56d66517.png">

This has happened multiple times after exiting this page.

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by kurtwheeler** [comment]
For the sake of reproducing this issue, what was the resource that you were trying to request?

**Comment by jaclyn-taroni** [comment]
`Chante's Mouse Model IDH2 AML Gene Expression Dataset` https://staging.resources.alexslemonade.org/resources/18

**Comment by kurtwheeler** [comment]
I was able to do this!!!
