### ISSUE TITLE
How will members join organizations?

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#53]
### Context

Our data model has organizations that will have an owner and then other members.

### Question

How will a member be added to an organization?  Does a user get a invitation or do they request to be allowed in? I guess depending which way it goes we' also need to allow accepting an invitation or approving a request?

Tagging @dvenprasad for an answer.

**Comment by dvenprasad** [comment]
We should allow both invites and request to join, **but for MVP, let's do invites only**. 

For requesting to join a lab, we'll need to provide a mechanism to find people on the portal and their labs, like a member directory or something.... I don't think this is super important for MVP.

**Comment by kurtwheeler** [comment]
Ok, so then we probably need to have a OrganizationInvitations table so we can track these. I'm thinking we can use one table for both directions, with a field that indicates whether it's a invitation or a request.

Initial fields for this model:
```
requester: User
request_receiver: User
organization: Organization
invite_or_request: String (choices: INVITE or REQUEST) (default INVITE)
status: String (choices: PENDING, ACCEPTED, REJECTED) (default: PENDING)
created_at: datetime
updated_at: datetime
```
Basic idea is that the `requester` sends an OrganizationInvitation to the `request_receiver` to join `organization`, unless `request_or_invite == REQUEST`, in which case the requester is asking to join `organization` instead. The status is updated when the request is accepted or rejected by the `request_receiver`.

**Comment by davidsmejia** [comment]
I was thinking of potential issues after discussing with @kurtwheeler, for after the MVP, it might make sense to add an additional status of `INVALID` or `EXPIRED` to account for requests made by a previous owner of an organization whom no longer has perms to modify the members at time of request being accepted (or would have been accepted).
