### ISSUE TITLE
Can not link grants after joining Team Jacob

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/resources-portal#531]
### Context

Using the resources portal invite link, I originally created my sandbox ORCID without a family name. This meant my account wasn't working properly. I updated my sandbox ORCID to include a family name, which fixed a number of issues I was experiencing. After I was added to Steven's team, it told me I had no grants to link.

@kurtwheeler asked me to create a new account using the invite link. Here's what happened next!

### Problem or idea

It linked up with my existing account. 

<img width="1582" alt="Screen Shot 2020-10-09 at 3 09 50 PM" src="https://user-images.githubusercontent.com/19534205/95623077-b07c7d80-0a42-11eb-948b-d9c911548d7e.png">

It told me I had two grants.

<img width="1582" alt="Screen Shot 2020-10-09 at 3 09 56 PM" src="https://user-images.githubusercontent.com/19534205/95623080-b07c7d80-0a42-11eb-9963-95d221ee328b.png">

When I navigated to Teams, my grants had disappeared.

<img width="1582" alt="Screen Shot 2020-10-09 at 3 10 12 PM" src="https://user-images.githubusercontent.com/19534205/95623081-b07c7d80-0a42-11eb-8750-04e5a26c5176.png">
<img width="1582" alt="Screen Shot 2020-10-09 at 3 10 19 PM" src="https://user-images.githubusercontent.com/19534205/95623135-c1c58a00-0a42-11eb-8678-d35c03142029.png">

But when I look under `Basic information`, I also have no grants. Because I had some weirdness early on, this might be difficult to parse!

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by davidsmejia** [comment]
As far as I know this should be fixed, the issue was at time of account creation the grants that are listed are just what we parsed from the url... , we actually associate them after you say they look good. We should probably revise this if there is a recurring issue but I havent been able to recreate that.

**Comment by kurtwheeler** [comment]
I verified that I could link a grant to someone else's team that I had been added to!
