### ISSUE TITLE
Notification count is not stable

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/resources-portal#534]
### Context

When browsing around the site, my notification badge changes numbers sometimes.  
The first place I noticed was starting here:
https://staging.resources.alexslemonade.org/account/manage-resources

Possibly related to #506 

### Problem or idea

I am attaching 3 screenshots, taken on successive pages as I clicked around the site. You will see that the notification number started at 2, then went down to 1, then to zero. If I caught it right when it changed, I could go back a page and get the number to increase again. But now it seems to have gone down to zero and stays there.

<img width="1078" alt="Screen Shot 2020-10-09 at 5 34 28 PM" src="https://user-images.githubusercontent.com/20483/95633738-55ed1c80-0a56-11eb-8975-725844f50a8b.png">
<img width="1078" alt="Screen Shot 2020-10-09 at 5 34 39 PM" src="https://user-images.githubusercontent.com/20483/95633746-5a193a00-0a56-11eb-8aa0-8dc4eaac8126.png">
<img width="1078" alt="Screen Shot 2020-10-09 at 5 37 46 PM" src="https://user-images.githubusercontent.com/20483/95633752-5c7b9400-0a56-11eb-955e-9f1c3e5b7e60.png">

### Solution or next step

I kind of assume this is somehow related to #506, so I think the next step is to look into the notification system in general.

**Comment by kurtwheeler** [comment]
@davidsmejia did this get addressed along with #506?

**Comment by davidsmejia** [comment]
> @davidsmejia did this get addressed along with #506?

I am going to close this issue and reference it in #506. I have not had a chance to get to that issue at the moment.
