### ISSUE TITLE
EndToEndTest Set up organization with two users

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#54]
### Context

I've created a set of end to end tests for us to implement: https://github.com/AlexsLemonade/resources-portal/issues/49

### This test should test:

Two users create accounts, one creates an organization, adds the other user to it, grants approval permission, then lists a resource in it

#### The test should do that by making the following API calls:
1. Create account Prof
2. Create account Postdoc
3. Prof creates organization Lab with grant id.
4. Prof invites Postdoc to join Lab.
5. Postdoc accepts invitation to join Lab.
7. Prof lists resource under Lab.
8. Prof removes all notification settings.

#### This test should test that the following notifications occur and no more (see https://github.com/AlexsLemonade/resources-portal/issues/51):
- [ ] The Postdoc receives a notification that the Prof invited her to join her lab.
- [ ] The Prof is notified that Postdoc accepted her invitation.

**Comment by dvenprasad** [comment]
Yeah...we want to notify what permissions they have once they accept invite/join request is approved. 

Also, when their permissions are modified.
