### ISSUE TITLE
EndToEndTest User creates account, requests a resource, and has her request fulfilled.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#55]
### Context

I've created a set of end to end tests for us to implement: https://github.com/AlexsLemonade/resources-portal/issues/49

This issue relies on the test data created by https://github.com/AlexsLemonade/resources-portal/issues/50

### This test should test:

User creates account, requests a resource, and has her request fulfilled.

#### The test should do that by making the following API calls:
1. Create account (Requester)
2. Search resources
3. Select two resources from PrimaryLab and requests them, uploading two signed IRBs
4. Postdoc approves the request and
5. The Requester uploads two signed MTAs
6.  Postdoc uploads executed MTA/IRBs
7. Postdoc marks the request fulfilled. (Separate from uploading MTA because it might take a while to ship out the resource.)

#### This test should test that the following notifications occur and no more (see https://github.com/AlexsLemonade/resources-portal/issues/51):
- [ ] The Postdoc receives a notification that a resource was requested
- [ ] The Requester receives a notification that her request was approved.
- [ ] The Postdoc is notified that the MTA was uploaded.
- [ ] The Requester is notified that the executed MTA/IRB were uploaded.
- [ ] The Requester receives a notification that her request was fulfilled.

@dvenprasad Do we want to add fields to the material_request table `reviewer_fulfilled` and `requester_fulfilled` to denote which users think it is fulfilled?

I'm assuming we want to have the Requester get a notification about her request being fulfilled, but do we want to have the Postdoc get a notification if the Requester acknowledges that she received the materials? Perhaps there's an option to be notified but it's off by default?

**Comment by dvenprasad** [comment]
For resources which need shipping, they are more likely to use the tracking number to track it down. I don't know if it's worth providing another check-point.

The resources which don't need shipping, (dataset and protocol), the feedback is instantaneous.

We can use those two fields as a quality check but I suspect it will be difficult for us to get `requester_fulfilled` information because people might be less motivated to answer once they have the resource. (i could be wrong, and be gladly wrong)

**Comment by kurtwheeler** [comment]
Yeah I had that thought as well. It'd be tricky to tell when people didn't actually receive their materials by looking at the reported positives. I think we should nix `requester_fulfilled`.

I think we should probably have a `is_fulfilled` field though so we can filter out fulfilled requests when showing users the requests they have assigned to them, right? (`is_fulfilled` because we no longer need to differentiate between requester and reviewer.)
