### ISSUE TITLE
Fulfilled requests should not be active?

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/resources-portal#551]
### Context

I received a resource request and "fulfilled" it. Then went back to my requests overview. https://staging.resources.alexslemonade.org/account/requests

### Problem or idea

I was expecting to see that I had no "Active" requests, but it seems that "Fulfilled" requests are still counted as active? I would not have expected this, as there is nothing more I can do at this time. 

 In general it is unclear what constitutes an "Active" request. What categories fall into this set?

### Solution or next step

Modify logic to not count "Fulfilled" requests as active and/or offer a better explanation of what active requests are.

**Comment by kurtwheeler** [comment]
I will add a `is_closed_sharer` property to the model and filters.
