### ISSUE TITLE
EndToEndTest New resource is listed and requested

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#57]
### Context

I've created a set of end to end tests for us to implement: https://github.com/AlexsLemonade/resources-portal/issues/49

This issue relies on the test data created by https://github.com/AlexsLemonade/resources-portal/issues/50

### This test should test:

A new resource is listed for PrimaryLab and a request is fulfilled for it. (tests that Postdoc has permission for new resources)

#### The test should do that by making the following API calls:
1. The PrimaryProf lists a new resource with PrimaryLab.
2. SecondaryProf requests the resource.
3. Postdoc approves the request.
4. SecondaryProf upload the signed MTA.
5. Postdoc uploads the executed MTA.

#### This test should test that the following notifications occur and no more (see https://github.com/AlexsLemonade/resources-portal/issues/51):
- [ ] The Postdoc receives a notification that a resource was requested
- [ ] SecondaryProf is notified that her request was approved.
- [ ] Postdoc receives notification that SecondaryProf has signed MTA.

**Comment by dvenprasad** [comment]
Step 3 should be just Postdoc approves request
4. SecondaryProf is notified to sign and upload the signed MTA.
5. Postdoc is notified and signed and uploads the executed MTA. 

So, for notifications, I would add
- [ ] Secondary Prof is prompted to sign and upload MTA. ( this can be in the same notification as approval notification, so feel free to ignore this one.)
- [ ] Postdoc receives notification that SecondaryProf has signed MTA.

IRB is only for review purposes, no action needs to be taken on it by Sharers.
