### ISSUE TITLE
Migrate staging metadata attributes

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/resources-portal#578]
### Context

After [#571](#571 ) then update the fields changed in this PR https://github.com/AlexsLemonade/resources-portal/pull/543/files

### Problem or idea

Some staging materials have additional_metadata keys that contain uppercase we have since made them all lower. The PR above shows which attributes that needs to be migrated.

### Solution or next step

Run the migration for the attributes change in 543

**Comment by Philinphiladelphia** [comment]
I checked for all the attributes mentioned in the linked PR. Looks like there were no PDX's currently on the staging server, so nothing needed to be migrated. The migration tool is up and running though!
