### ISSUE TITLE
Handle bad grant data/no grant data invites

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#589]
### Context

Came up during sprint planning. 

### Problem or idea

When users try to create accounts vis the invite link and grants data is weird or does not exist, users should not be allowed to create accounts instead, be asked to reach out to us so we can fix it. i.e send them a valid invite link. 

This is the message we want to display
`Uh-oh, we've encountered a problem creating this account. We are unable to proceed with the sign up process. Please reach out to the Grants team so we can send you a new invite link` 

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by kurtwheeler** [comment]
@davidsmejia has this been addressed in any way?

**Comment by davidsmejia** [comment]
> @davidsmejia has this been addressed in any way?

No this is not what we implemented for this scenario but we can do this.

**Comment by kurtwheeler** [comment]
> this is not what we implemented for this scenario

Did we implement something else for this scenario?

**Comment by davidsmejia** [comment]
> > this is not what we implemented for this scenario
> 
> Did we implement something else for this scenario?

We currently just create grants for anything that we can and then tell the user to contact the grants team if anything looks fishy/ missing.

**Comment by kurtwheeler** [comment]
Ah okay then!
