### ISSUE TITLE
Files need to be uploaded twice to work

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#598]
### Context

When uploading files, selecting the file to upload the first time, prompts to select a file to upload again. It always works the second time. 

### Problem or idea

_The context should lead to something, an idea or a problem that you’re facing. Put that here._

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by jaclyn-taroni** [comment]
Duplicate of #593?

**Comment by dvenprasad** [comment]
Yes, marking it as duplicate and closing it.
