### ISSUE TITLE
Show Team Name on Resource review page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#601]
### Context

<img width="1139" alt="Screen Shot 2020-11-05 at 4 47 29 PM" src="https://user-images.githubusercontent.com/15315514/98299988-9fae2180-1f86-11eb-99c2-1166b7516538.png">

### Problem or idea

Team name is not displayed here. Show the team name for consistency. 

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by kurtwheeler** [comment]
Add one more column for Team Name and transpose the table.
