### ISSUE TITLE
Search Cards: Labels missing

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#619]
### Context

On request cards the following fields are labels:
- Publication / Pre-print
- Request Requirement

### Problem or idea

Add them. 

Also, these fields show be shown even if they are empty. If they are empty, then we should show None. 

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by davidsmejia** [comment]
@dvenprasad Would you be able to send me a screen shot please? I'm not 100% sure which request card you're referring to.

**Comment by dvenprasad** [comment]
Oh.... ohhh.... oh!  Sorry my bad.... I meant search cards. 


![Screen Shot 2021-01-13 at 9 26 53 AM](https://user-images.githubusercontent.com/15315514/104464945-7e1e7700-5581-11eb-8c9b-570d301598d8.png)

**Comment by dvenprasad** [comment]
Also, the `Link to Publication` should be whatever value user provides for `Publication Title` or `Pre-print Title` 

![Screen Shot 2021-01-13 at 1 59 37 PM](https://user-images.githubusercontent.com/15315514/104496998-b89b0a80-55a7-11eb-933c-6150f83c534d.png)


![Screen Shot 2021-01-13 at 2 00 02 PM](https://user-images.githubusercontent.com/15315514/104497017-c05aaf00-55a7-11eb-95d0-a21f5aa85376.png)

For Imported Resources:

![Screen Shot 2021-01-13 at 2 00 25 PM](https://user-images.githubusercontent.com/15315514/104497059-cfd9f800-55a7-11eb-9c6e-4002594c3a18.png)

**Comment by davidsmejia** [comment]
closed with #736
