### ISSUE TITLE
Team/Notifications: People not part of portal do not receive invites

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#630]
### Context

People with no accounts on the portal do not receive an invite to create an account on CCRR portal. 

### Problem or idea

They should receive an email telling them to create an account on the portal.

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by kurtwheeler** [comment]
As far as I can tell, this is a frontend issue. I don't see any network calls to `/email-invitation/` when I try to invite `kurt.wheeler91+notamember@gmail.com`.
