### ISSUE TITLE
Request: Open request, requester, provide info about next steps.

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#632]
### Context

<img width="797" alt="Screen Shot 2020-11-12 at 8 41 57 PM" src="https://user-images.githubusercontent.com/15315514/99018203-89c0d380-2527-11eb-99eb-b4fc8a8aedc8.png">

### Problem or idea

It would be good to put a message here saying something along the lines "Hey <sharer>/ <team name> are reviewing your materials." 

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by davidsmejia** [comment]
This actually should be fixed now.

**Comment by davidsmejia** [comment]
![Screen Shot 2021-02-12 at 4 57 11 PM](https://user-images.githubusercontent.com/1075609/107826721-5b83a780-6d53-11eb-8e95-38780a2f03ed.png)
