### ISSUE TITLE
Something weird with Requests math

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#642]
### Context

This resource was requested only once but it says it's got 1 open request and 1 closed request. 
<img width="790" alt="Screen Shot 2020-11-13 at 4 03 14 PM" src="https://user-images.githubusercontent.com/15315514/99120964-c3e2b180-25c9-11eb-8c9e-2ffb3fc2590e.png">

### Problem or idea

This page should have no open requests and 1 closed request.
 
Possibly related #616, #551 

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by davidsmejia** [comment]
Closed with #717
