### ISSUE TITLE
Add examples of input formats expected for imports

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#654]
### Context

Suggestions by Anna

### Problem or idea

Add examples as guides below form field label
<img width="736" alt="Screen Shot 2020-11-17 at 8 21 23 AM" src="https://user-images.githubusercontent.com/15315514/99395070-e7e61180-28ad-11eb-9f42-f586aa79d61d.png">

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by davidsmejia** [comment]
https://github.com/AlexsLemonade/resources-portal/pull/734

not sure why it didnt show that it was referenced
