### ISSUE TITLE
Copy changes on List Resource before we start page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#659]
### Context

Suggestions by Anna

### Problem or idea

```
Update “Before we get started, here are a few things to keep handy:”
“If your institution requires a Material Transfer Agreement (MTA) to share, you will need to upload it in order to list your resource.”
“…imposed by you or your organization (e.g. cannot ship internationally or can only ship via specific providers such as UPS or FedEx).”
“Please be aware that you are responsible for administrative activities such as reviewing and responding to requests and shipping/sending resources to requestors. We only provide the infrastructure to enable sharing and improve transparency during the sharing process.”
```

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by cgreene** [comment]
I'm not sure how good and easy to use the i18n software is for react/redux, but I do find myself wondering if exporting the string content of the portal with one of these systems could be useful. This could allow easier editing by team members without specialized skills (and, eventually, internationalization if ever required). Cost/benefit of this depends on how painful it would be to do.
