### ISSUE TITLE
Provide `Please specify` text input when users select `other` as payment option

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#660]
### Context

Suggestions by Anna

### Problem or idea

`
For ‘Requester is responsible for shipping costs’, what is ‘other’? Should we ask them to comment in the box below? Otherwise it’s not providing the Requestor any usable information. If we have them use the box below, maybe we change the name to “Shipping Comments”?
`

When users select other, we should present users with a text input with Please specify label.

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by davidsmejia** [comment]
Itemized tasks

* Add a `payment_method_sharer_notes` to material model charField text
* Add the textbox when `Other` is selected to fill out payment_method_sharer_notes
* When Other Payment Methods is selected in `AwaitingAdditionalDocumentsForm` show `payment_sharer_notes` above in an InfoCard
* show payment_sharer_notes under accepts other payment methods in all request requirements list components
