### ISSUE TITLE
Update placeholder copy on active sent requests page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#663]
### Context

Suggestions by Anna

### Problem or idea

>After cancelling my Anna Test protocol request, it says I have not received or made any requests yet. Perhaps this phrasing should change to not having any active requests instead of saying you haven’t made any requests yet (since I did make one, but cancelled it)?
After making another request, it now says I have 1 active request, so it’s just the in between state of not having active requests where it says you have not received or made any requests

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by davidsmejia** [comment]
Instead of changing the copy we will be addressing this by adding a "Closed" tab and overview card. 
Issue #641 
PR #733
