### ISSUE TITLE
Create Accounts/ Login

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#7]
### Context
Users will need accounts to list, requests, and add questions.

### Problem or idea

Users can only create accounts/login with ORCIDs

### Solution or next step

https://members.orcid.org/api/integrate/orcid-sign-in

**Comment by dvenprasad** [comment]
- Looks like ORCID provides one button for both connecting and creating ORCID.  https://members.orcid.org/api/resources/graphics

- On our end, when we prompt the user to login/create account with ORCID, we should have a small sentence what ORCID is. ORCID website and documentation does a really good job of clearly explaining what it is, so I will creatively lift the language from there. We should consider linking out to either this [documentation page](https://support.orcid.org/hc/en-us/articles/360006897334-What-is-my-ORCID-iD-and-how-should-I-use-it-) or [this article](https://orcid.org/blog/2018/07/27/six-ways-make-your-orcid-id-work-you)

- List of places(for which we have design) where we will need to prompt/indicate users to login/create an account to continue
   - [On the list resources page](https://invis.io/NAVYSEBXJCF#/404857872_list-Resources)
   - Replace `Request Resource` button with `Login to Request` 
   - Add login and create account buttons to nav bar 
   - Log in to contact requesters with queries (?) ([this page](https://invis.io/NAVYSEBXJCF#/408945788_view-Cell-Line-Contact))

**Comment by dvenprasad** [comment]
More relevant ORCID docs:

- [icons](https://figshare.com/articles/ORCID_iD_icon_graphics/5008697)
- [Presenting oauth](https://members.orcid.org/api/oauth/presenting-oauth)

**Comment by davidsmejia** [comment]
Below client.org is the domain of the resource-portal front end client and api.org is the url for the api

The Oauth flow would work this way for our needs:

* User navigates to login area and clicks login w/ orchid button
* Popup window opens @ Orcid domain to signin or create account
* User enters creds or creates account
* On Successful Authentication
  * User is redirected to client.org/login/success?token=xxx-token
  * The client posts to api.org/login/xxx-token (show activity indicator)
  * The api fetches the orchid id and various info with provided token
  * If token is good API creates a user token and returns it (creates user record if first login)
  * client.js then updates UI to indicate that the user is logged in (success alert or redirect)

Bad flow should either show error alert saying authentication failed as failure can happen:
* when redirected from Orcid to client.org/login/error
* when our api tries to fetch data from orcid (expired token )
* this should take them back to client.org/login to sign back in with orcid

We should consider adding a button to explicitly fetch latest orcid details into our system if we don't want to try updating it on every auth which might not be often enough, we should allow a manual update 2x per day to prevent being rate limited from orchid. 

Still thinking about:
* We need to make sure we can log users out without being too disruptive to their flow.
* We need to be able to get refreshed tokens before the existing tokens expire or they would have to sign back in through the oauth flow (which is ok if they come back after a long time but not ok if they are in the middle of using the system)

**Comment by dvenprasad** [comment]
**Low-fis**
![create-account-nav-bar-modal](https://user-images.githubusercontent.com/15315514/81207462-91615780-8f9b-11ea-8531-4aa201781fcb.png)
![login-to-contact](https://user-images.githubusercontent.com/15315514/81207471-945c4800-8f9b-11ea-860a-b51a93b360b3.png)
![login-to-request](https://user-images.githubusercontent.com/15315514/81207474-97573880-8f9b-11ea-9271-26bba56d51bf.png)
![login-common-login-modal](https://user-images.githubusercontent.com/15315514/81207477-98886580-8f9b-11ea-89b3-95ea00632b0f.png)
![login-to-list](https://user-images.githubusercontent.com/15315514/81207484-9b835600-8f9b-11ea-89a5-bf89e610eeb5.png)
![create-account-nav-bar](https://user-images.githubusercontent.com/15315514/81207493-9f16dd00-8f9b-11ea-8833-9a734c269cf6.png)

**Comment by dvenprasad** [comment]
**High-fis**
![view-cell-line-login-to-contact](https://user-images.githubusercontent.com/15315514/81207766-13518080-8f9c-11ea-81c4-20e2349bfa14.png)
![create-account-modal-view-cell-line](https://user-images.githubusercontent.com/15315514/81207767-13ea1700-8f9c-11ea-84e2-2a9dad6aae57.png)
![list-resources-not-logged-in](https://user-images.githubusercontent.com/15315514/81207770-1482ad80-8f9c-11ea-8d9c-018ea6b9a1a6.png)
![list-resources-login-modal](https://user-images.githubusercontent.com/15315514/81207769-13ea1700-8f9c-11ea-9544-f94a285d051e.png)


**Invision Link**: https://invis.io/NAVYSEBXJCF#/414927119_list-Resources-Not-Logged-In
**ORCID iD icon:** https://projects.invisionapp.com/assets/19276522/742221436/7698E49C7AD59435FF1DF85FA8274F1966920E8B7F7DEEE146B06B8DC8C8CED9

@davidsmejia let me know if you need anything else
