### ISSUE TITLE
Add a mechanism for users without grant id to let us know they want to add resources

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#737]
### Context
Currently, the portal does not allow users without a grant id to add resources or create teams. 

### Problem or idea

Add a button somewhere (My Account seems to make the most sense/ or on Add resources page) for them to let us know that they would like to be able to add resources. This would be good to collect information to understand when to prioritize #215 . 

### Solution or next step

Design and implement a mechanism for this after beta but before launch

**Comment by davidsmejia** [comment]
Since users don't know that they can't add resources without one. I think we could also add a separate guard that prevents people from going to the list/import form pages, right now, they wont be able to get past the select grant step. If we catch them earlier in the process (we can check that they don't belong to an org, or if they do their orgs have no grants) we could present a button on the `/resources` page to collect that info.

**Comment by dvenprasad** [comment]
The best places to provide them this button is when we require Grant ID to do a thing. There are three places
- Listing a resource
- Importing a resource
- Creating a team 

We can prompt at these places to let us know if they wish to list resources without a grant ID.  @davidsmejia  mentioned yesterday, we can do a fullscreen takeover and ask them to let us know. 

Maybe we should track this in a google/hubspot form instead of an email to grants team (harder to keep track). It maybe easier for us measure interest and to reach back out when we do let people list without grant ids. Am I over engineering this? @jaclyn-taroni

**Comment by jaclyn-taroni** [comment]
> Maybe we should track this in a google/hubspot form instead of an email to grants team (harder to keep track). It maybe easier for us measure interest and to reach back out when we do let people list without grant ids. Am I over engineering this?

Would you couch it as sign up to be notified if we add this feature? It makes sense to me that I would enter my email if that was the prompt -> a list on HubSpot. I imagine if someone is highly motivated to draft an email that provides a lot of additional context that we may find useful, they would probably find a way to send that email if that makes sense.

**Comment by dvenprasad** [comment]
Yeah I think getting their email would be one of the questions on the form. We can always provide a box for them to tell us things or ask for specific information we may want to know, like what do they want to share? (although I'm not sure how to phrase that last question with less scoopy vibes)

I was thinking of couching it as, hey we're measuring interest in providing this feature.

**Comment by dvenprasad** [comment]
![list-resource-no-grant-id](https://user-images.githubusercontent.com/15315514/109862999-1acece00-7c2f-11eb-833d-9b8e93ac7e97.png)



I created a hubspot form to track the responses from this. Below is the embed code:

```<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	portalId: "5187852",
	formId: "960eaa6e-dc9a-4921-874f-40ba9bae8583"
});
</script>```

Invision link: https://invis.io/NAVYSEBXJCF#/446420775_list-Resource-No-Grant-Id
