### ISSUE TITLE
Citation field values does not register while importing dbGaP

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#748]
### Context

Importing a dataset from dbGaP. Added some thing the citation field. It did not stick. See attached screenshots

### Problem or idea
![Screen Shot 2021-02-03 at 12 01 41 PM](https://user-images.githubusercontent.com/15315514/106782730-8580ef80-6618-11eb-9066-70cd10f07e6e.png)

![Screen Shot 2021-02-03 at 12 01 48 PM](https://user-images.githubusercontent.com/15315514/106782757-8e71c100-6618-11eb-949b-e765f08a90f6.png)

![Screen Shot 2021-02-03 at 12 02 09 PM](https://user-images.githubusercontent.com/15315514/106782777-92054800-6618-11eb-883f-33e34eab2b24.png)

### Solution or next step

It should work. Not sure if this error applies to other fields/ resources. We should check and address it.

**Comment by dvenprasad** [comment]
Same error for importing from AddGene

**Comment by davidsmejia** [comment]
in `PublicationInformation` citation is no longer nested in additional_metadata
