### ISSUE TITLE
ATCC Imports: Additional fields + other field configs

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#751]
### Context

Importing from ATCC

### Problem or idea
- Same issue as #749, fields not in the import form, shows up on review and view resource pages
- Number of Available Cell Lines should not be on the import  form
- Disease, Age, Ethnicity should be optional fields

![Screen Shot 2021-02-03 at 2 31 13 PM](https://user-images.githubusercontent.com/15315514/106800352-570e0f00-662e-11eb-835a-c0b9d4e43c57.png)

![Screen Shot 2021-02-03 at 2 31 36 PM](https://user-images.githubusercontent.com/15315514/106800386-62613a80-662e-11eb-9643-d68907a8ceba.png)

**Comment by davidsmejia** [comment]
Note : 
pass `optionalAttributes` from `useResource` to the `ResourceFormField` in `ResourceEditImportedForm`
