### ISSUE TITLE
User encounters error when they report missing/incorrect info

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#791]
### Context
User reported error.  

### Problem or idea

They tried to 'report missing/incorrect info' on `My Accounts` page and received an error. See attached screenshot
<img width="1752" alt="grant-error" src="https://user-images.githubusercontent.com/15315514/111326759-32e91900-8643-11eb-93aa-9f8c653d6987.png">

**Comment by davidsmejia** [comment]
Could I get some context for this.. I'm unable to reproduce this behavior.

**Comment by davidsmejia** [comment]
This has been working on local and staging so going to close for now.
