### ISSUE TITLE
User cannot login via Safari

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#803]
### Context

Sent user an invite link. 

### Problem or idea

They opened it using safari and tried do the ORCID authentication and it errored out but it worked on Chrome. 

### Solution or next step

Resolve this for safari.

**Comment by davidsmejia** [comment]
I'm closing this for now as I was unable to recreate it.
I tested the standard login, create account, and the redirects will be fixed with #831
