### ISSUE TITLE
Redirect user back to the page they were on when they logged in

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#804]
### Context

Found during eval. User signed in on resource details page

### Problem or idea

User signed in on resource details page and after signing them in, it took them to `My account` page. This should redirect them back to the page they were on since they are in the middle of a task there and taking them to `My account` is disorienting + they need to put the effort to navigate back the original page. 

### Solution or next step

We should just take them back to the page where they signed in whenever we have a CTA that says `Sign in to X`.

**Comment by davidsmejia** [comment]
Create account redirect back to where they were check for after the post new user

**Comment by davidsmejia** [comment]
duplicate of #831
