### ISSUE TITLE
Link from email lands user in a different session

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#820]
### Context

Came up during beta testing

### Problem or idea

User followed a link from their email notification to the portal. The link opened in a new tab but they were presented with a sign in page. The URL seemed correct but the title of the page was weird (see screenshot) I'm thinking it's a antivirus problem but wanted to make a note of it and see if there was anything we could do to help them troubleshoot out of it. 

![Screen Shot 2021-04-09 at 3 47 37 PM](https://user-images.githubusercontent.com/15315514/114233163-f0b5ad80-994a-11eb-82c1-175c1455ecfc.png)

### Solution or next step

How can we mitigate this, if we can?

**Comment by dvenprasad** [comment]
Good news is that when they hit sign in, they were automatically signed in and landed on the right page.

**Comment by davidsmejia** [comment]
Honestly, I think they will just have to suffer.

``` The Click-time URL Protection service "rewrites" and performs checks on certain URLs in emails that are delivered to your organization's end users. The process of rewriting allows the service to manage access to the URL to ensure the destination is innocuous.```
