### ISSUE TITLE
Cell Line Search card: popluate Tissue histology field

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#823]
### Context

Came across it during beta testing. User was going through search results of cell lines.

### Problem or idea

The tissue histology field showed up as `Not specified` for all of the results. 

We should populate it with the value in the `Tissue` field for the resource. If it makes it easier, we can rename the field on the search result card to `Tissue`

**Comment by davidsmejia** [comment]
Closed with #840
