### ISSUE TITLE
List of places to add help links

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#842]
### Context
Help section is getting written! 

### Problem or idea

This is issue is to compile a list of places on the portal where it would be useful to provide help links for additional context, how-tos, or troubleshooting. 

### Solution or next step

I'll compile the list as I work through the help section.

**Comment by dvenprasad** [comment]
https://knowledge.hubspot.com/knowledge-base/how-do-i-set-up-and-customize-my-knowledge-base

**Comment by davidsmejia** [comment]
Ok looks like it can be setup with a CNAME record we just need to know what we should point at it? `help.resources.alexslemonade.org`?

**Comment by dvenprasad** [comment]
- **Add resources page**
   - Import title
   - List title
 
- **Import/ List page**
  - Team field
  - Grant ID field

- **Requests Requirements title**
