### ISSUE TITLE
Implement initial version of the search page with a single resource type

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/resources-portal#91]
### Context

https://github.com/AlexsLemonade/resources-portal/issues/63
https://github.com/AlexsLemonade/resources-portal/issues/13

### Problem or idea

Add the search page, high-fi designs on https://github.com/AlexsLemonade/resources-portal/issues/13. For this one let's just:

- Add the search input at the top
- Leave the space for the filters (will file another issue for them)
- Decide how we are going to store the templates for each resource type and add one for GEO

Proposed URL: `/search/?q=mouse`

**Comment by davidsmejia** [comment]
closed with #63 + #153
