### ISSUE TITLE
Allow saving and restoring addresses in the request resource page

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/resources-portal#94]
### Context

#93 

### Problem or idea

Continuing with #93 we'll need the ability to store the addresses that users request, and allow them to select one if they entered it before.

![image](https://user-images.githubusercontent.com/1882507/78403514-7a110200-75ca-11ea-85c7-0a8ccdb922ba.png)

**Comment by davidsmejia** [comment]
I take it we should be able to read from existing addresses they have used, would this be an API endpoint?

**Comment by davidsmejia** [comment]
Replaced by #461
